### ISSUE TITLE
Show tippy as a reason for disabling on disabled q-btn. 

### ISSUE THREAD

**Issue by kub1x** [thecodewarrior/Tippy.vue#7]
This leads to two questions: 
* Is it possible to enable/show tippy, when a button is disabled? 
* Is it possible to disable/not show tippy, otherwise? 

I'd expect following code to work, but tippy won't show when disabled and it shows empty when enabled :-/ And it complains in console, that enabled ain't no prop of tippy. 

```
<q-btn 
    v-tippy='{ enabled: !buttonIsDisabled, content: buttonIsDisabledBecauseOfThis }' 
    :disabled='buttonIsDisabled' />
```

**Comment by thecodewarrior** [comment]
You can't do that with the directive form, because showing/hiding and enabling/disabling are method calls on the tippy instance, not properties. However, you can do it using the `<tippy>` component, since it has helper properties that make the necessary method calls.

If you just want to disable the tooltip when the `q-btn` is enabled, you would use the `:enabled` prop, which makes the necessary `.enable()` and `.disable()` method calls as needed:
```html
<q-btn v-tippy :disabled='buttonIsDisabled'/>
<tippy :enabled="buttonIsDisabled">{{buttonIsDisabledBecauseOfThis}}</tippy>
```
If that still doesn't work, it may be that `q-btn` is setting the `pointer-events: none;` CSS rule on the button, in which case wrapping the button in a div/span/whatever and adding the tooltip to that wrapper element should work.

If you want to completely override the mouse hover behavior and manually show/hide the tooltip based on a flag, you would set the `trigger` prop to `"manual"` and use the `:visible` prop, which calls `.show()` and `.hide()` as needed:
```html
<q-btn v-tippy :disabled='buttonIsDisabled'/>
<tippy trigger="manual" :visible="buttonIsDisabled">{{buttonIsDisabledBecauseOfThis}}</tippy>
```

Regarding the code you posted, the fact that you setting `enabled` has any effect at all is odd, but setting that aside, part of your issue is that you inverted your `buttonIsDisabled` flag. Right now you're enabling the tooltip when the button is *not* disabled, i.e. when the button is *enabled.* The reason the tooltip is empty is because when the button is enabled the `buttonIsDisabledBecauseOfThis` variable is probably empty.
